### ISSUE TITLE
"eb-wf03-01" dongle

### ISSUE THREAD

**Issue by sakhnik** [mihaigsm2003/Deye2mqtt---Read-data-from-Deye--Sunsynk-#1]
Hello! I've got a couple of "eb-wf03-01", but I'm struggling to find any info about the chip inside. Is it ESP8266 or any other? How do you build and flash firmware for it?

**Comment by sakhnik** [comment]
Well, I figured it out. It's ESP8266EX. To flash, the fifth pin should be grounded when switching on.

**Comment by yarosman** [comment]
> Well, I figured it out. It's ESP8266EX. To flash, the fifth pin should be grounded when switching on.

hello. can you share image with pin for flashing ?

**Comment by sakhnik** [comment]
![IMG_20240904_100021187~2](https://github.com/user-attachments/assets/b44c46f1-b9b2-42ac-ba71-38db3f8cc6be)
The horizontal pins are for flashing. I ground DL before powering the MCU to upload firmware. I assume UART0 is for communication via RS232. The vertical pins belong to UART1 for logging only.
I haven't succeeded in using the dongle to communicate with PowMr and Edecoa inverters. The controller is reset every 10 seconds. I will try other RS232 converters to establish communication and return to the dongle later.
Please let me know if you have any progress.
